### ISSUE TITLE
Crafting Table with a 9x9 Grid or a 6x6 Grid for advanced Recipes

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#104]
Crafting Table with a 9x9 Grid or a 6x6 Grid for advanced Recipes

**Comment by Dream-Master** [comment]
With Minetweaker support

**Comment by leftyde** [comment]
That would be awesome, but I hope with AE2 support as well :P?

**Comment by Drobac** [comment]
Indeed, opens up some interesting options

**Comment by Dream-Master** [comment]
I think make a 9x9 Crafting Table isn't that hard but i think to implement this in ae2 is a bit more complicated.

**Comment by Namikon** [comment]
The table itself should not a big deal at all, AE2 will only work if they have a decent API I can hook into.
But as this goal involves tileentities and some advanced mod-interaction, I won't start this until all other "small" projects are done

**Comment by Namikon** [comment]
Before we "reinvent the wheel", there is already a mod that provides a bigger crafting grid:
http://minecraftsix.com/extended-workbench-mod/

**Comment by leftyde** [comment]
or just a real assembly machine like the rocket crafting thingy from galacticraft, so you need a schematic and then you can simply imput items via automation and the table says, item A into slot 1, item B into slot 2 and so on? :D Would be much simpler but extrem nice :D

**Comment by Dream-Master** [comment]
Yes this is a very good Idea.

**Comment by Dream-Master** [comment]
But we need Minetweaker support for the table. I like the Idea make a Workbench like Galacticraft.

**Comment by leftyde** [comment]
I'm just starting learning C++ so I'm not an expert, especially not in Java but that should be the smallest problem right? :I I mean the only thing you have to minetweak would be a schematic item so why not say directly into that Item via NBT item 1 for slot 1 and the item you will get as an output so we don't have to modify much, because NBT of an Item can be already modified with MT

**Comment by Namikon** [comment]
Seems that modtweaker has support for it, at least you can find some code on GitHub for that. Anyways, the mod is "open source", i could easily strip the custom tools and make it into a new mod where we can change / improve whatever we need to.
@leftyde If you're familar with c++, java is a piece of cake compared to c/c++. (And you don't have to worry about pointers or segfaults, yay :P)

**Comment by Namikon** [comment]
I present you: The "F*ck you, that's why" Crafting Table: http://imgur.com/buVhX5n
Are you *absolutely* sure you want me to make this monster?

**Comment by Dream-Master** [comment]
I think a smaller one like 3*6 or 4*4 would be ok too. Maybe 2 different ones. But I think we have to think first witch recipes we want to put inside. For armor the 3*6 would be nice. For machines maybe a 4*4 or 5*5 and I thinks max 6*6 size. 9*9 is too big.

**Comment by Dream-Master** [comment]
Git hiding.  *

**Comment by Namikon** [comment]
Well, basically, the crafting grid is not limited in any way. It can be any size you can imagine (Well, at some point the recipe-lookup might cause issues, as the whole grid is parsed if you place/move one single item).

However, there should be indeed some *good* ideas what to craft (and HOW to craft) with a table that's larger than 3x3. Otherwise, it's just another way to "nerf it because it's there". I think there is a reason why (almost) no mod out there has a larger crafting area than 3x3, ChromatiCraft implements a 5x5 crafting area, but it has a different mechanic which is pretty interesting itself. Galactricraft is not square-sized, but instead you are placing parts in a specific pattern of the machine your are going to build. We can copy that, but that's boring. 

By the way: I couldn't resist... Took me about 45 minutes: Giant's axe anyone? https://unsee.cc/zupinamo Doesn't do anything yet but.. yeah.. Proof of concept thingy.
And.. to be honest, even if it looks funny, just *trying* to imagine gregtech recipes in such a grid is a nightmare

**Comment by Drobac** [comment]
with those kind of recipes i think its only appropriate that those tool have the size of TF's Giant Sword / pickaxe :)

**Comment by Drobac** [comment]
Also i agree that just because there would be a 9x9 crafting grid that we have to use 9x9 recipes but utilizes a logical shape or mechanic

**Comment by leftyde** [comment]
That's why I think a real "assembly" table would be the better way and could easily work with the gregtech tier system :I? Schematic + materials + tier = speed and success? XD (So wrong tier = lower success chance :D)

**Comment by Namikon** [comment]
I like the idea about schematics for certain (high-tier? rare?) items. IMHO, the basic goal of such a mod should be
- Prevent the player from being able to craft/use end-game items before they reached a certain point

You can always be lucky and find a village/dungeon with chests that help you out with (in our case) steel. So, my initial ideas about that mod where:
- The more you craft, the more "experience points" you get
- With those points, you'll be able to "level up" your crafting system, which eventually unlocks higher tiers
- The mod could keep track of the things you crafted, and prevent you, for example, from placing it into the world until you made one yourself. Not as easy, but kinda the same could work with item-usage. In order to use it, you have to craft it. (Or something that will unlock you to do that. Like you could define all MV machines from GregTech to be "Tier 2", and you can't place them/open the GUI until you reached that tier)
- To automatically unlock new "tiers", the mod could also keep track of places you've visited, mobs you've killed, blocks you've "seen", etc. 

About a "success chance".. Well.. That could be an optional setting. I wouldn't enfore such an item-loss by random chance.

**Comment by Dream-Master** [comment]
Yes this Idea sound very good.

**Comment by Drobac** [comment]
Well if you want to do something like this you dont even have to set it for all items of a certain tier since i guess it would be problematic, the easiest way to do iit for GT would be to make the electric motors or the machine casings craftable only in the assembler so that you always need the assembler of that tier to progress further (woulld need some tweaks in the recipe for making the assemblers). Or do a similllar thing to galacticraft tiers but make the plans for the new items not drop from bosses, as i think that would be tricky to do for alll the things. But make it so the plans are crafted from items only available on that tier, either machines or specific product availlble by using the machines of that tier

**Comment by Namikon** [comment]
What I have done so far (Call it "pre-Alpha") is:
I created an event-Like System that is able to track a player's actions without the requirement of adding mods as dependency, which basically enables the user of the API to just ask for stuff like "Has Player X seen Block Y?" or "Has Player X killed mob Y yet?" stuff like that. I will add as much as possible to this System, so you eventually could even track how long the player was idle, or how many blocks he has fallen yet without dying.

Next thing i'm gonna add is something that enables you to add certain stages (Compared to a "tier"), where a "stage" defines itself as a set of events a player has done. A higher "stage" will unlock once you have achieved all previous event-goals. Be it automatically, or by using an Item that has to be crafted, compared to the Thaumcraft Research. I think that will be configurable then.

Of course, it will be without any limit of how many events you add for a single stage, or how many stages you add in total. (So adding 9001 Stages and call the last one "It's over 9000" is possible, yay (And yes, I know it is 8000 in the original series, but.. yeah..))

As for the crafting, i'll keep that separated from the stage-system itself, as it will force me to make it independent, and eventually it will be a mod that can be used by other people to add advanced tiering to their mods aswell without bothering about tracking a player's actions.

**Comment by Namikon** [comment]
Closed because we came to the conclusion that just by having a larger grid than 3x3 doesn't make sense without a proper tiering that is bound to the player himself. And that tiering is currenctly WiP by me, but will take some more time to finish.
