### ISSUE TITLE
Enchanted Armor with Recipes

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#131]
Make Enchanted Armor with shaped Recipies.

Good Idea?

**Comment by Namikon** [comment]
As I mentioned already, there is some kind of progression for your first weeks, that would be:
Tinkers Wood, Iron, RailCraft Steel, IronWood, SteelLeaf. We first have to make sure that this Armor is enough (Without potions!) to kill the Naga boss. Once a few people have tested that, we will know if there is a requirement for new armor or not

**Comment by Drobac** [comment]
You cannot kill the naga with normal armor (even enchanted) without potions. Tried and tested

**Comment by Dream-Master** [comment]
So which enchant you need? Is iron wood and steel leaves enough to or we have to make basic enchanting crafting recipes for armor?

**Comment by Drobac** [comment]
No amount of enchant will help, you need at least some kind of regen, otherwise you usually die in abou 20 seconds

**Comment by Dream-Master** [comment]
regen isnt a enchant ? Golden Apple?

**Comment by Drobac** [comment]
well i dont consider it an enchant, its a potion effect and at least i see the golden apple as a potion

**Comment by Drobac** [comment]
Naga can even be killed without armor if you have a really good fast bow and a lot of luck, but if it gets to you it hits hard

**Comment by Namikon** [comment]
It again depends on how you want Thaumcraft to be tiered.
If you decide to make it hard, it will be midgame before you can even start with Thaumcraft. The first boss should not require luck or mega armor/weapons to defeat, as you have to reach a certain tier before you can craft your first "next-gen" (nano) armor. Which might not be possible at all if you need some aspects of thaumcraft in order to progress.

If it's pure optional if you do thaumcraft and reach full nano-armor without anything that's tiered behind thaumcraft, then it's fine. But I think it has to be recorded somewhere, so we can (for ourself and later for the questbook) keep track on when which mod shall become available and when it's meant to be played at all.

@Drobac Can your bow/arrows be crafted without having access to anything thaumcraft related and probably mv/hv range?

**Comment by Drobac** [comment]
Just a regular short bow made of manyullium, thaumium and fiery string only leveled up and upgraded a bit. Same with the arrows. If you keep shooting him he basically stays in the same spot, so with a fast enough bow, doesnt even have to be too strong you can kill it

**Comment by Namikon** [comment]
Well.. Thaumium is not available. Or did you mean "Manyullium _or_ Thaumium, and fiery string" ?

**Comment by Drobac** [comment]
Probably works with shurikens as well, think they got good attack speed. And i meant 2 bow limbs - one thaumium one manyullium

**Comment by Namikon** [comment]
So I guess the thaumium is optional and can be replaced with manyullium then, for the soon-to-be-thaumaturgist. Golden apples are an option too, as you can find a bunch of small gold ores in the overworld, and you barely need any gold before you reach HV. Not 100% sure if you can _craft_ those apples with 32 eu, but i think there might be even a recipe for tinkers

**Comment by Dream-Master** [comment]
So not neede atm.  We can reopen it or make a new Issue when needed.
