### ISSUE TITLE
Malis Doors Mod

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#132]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-7-10-1-8-1-digicode-25-05-2015-see

**Comment by Drobac** [comment]
Looks interesting, but we got carpenters blocks for all sorts of doors already

**Comment by Dream-Master** [comment]
So we don't need?

**Comment by Drobac** [comment]
Wait for more votes

**Comment by Namikon** [comment]
It would be a pure visual mod, except the player-detector that provides a strong redstone signal to all adjacent blocks once a player is nearby, which is pretty nice for automated doors without pressure plates. Malis doors however overrides vanilla doors to provide smooth door/fence animation and i had (visual only) glitches with that on my server. But we never removed it because you can do a lot of cool stuff (And it's fixed in the most recent version anyways I guess).

I also had Carpenters doors installed, they both work fine together. What you can do is build a garage door that slides open; I build a rocket center for my Galacticraft stuff and the main door is a 8x5 garage door :)

**Comment by Dream-Master** [comment]
I add it in the new update together with wireless red stone and translocaters and project red

**Comment by Namikon** [comment]
Mod is added and pack is running
