### ISSUE TITLE
Mutagen made out of uran and bacterial sludge in the hv mixer

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#145]

**Comment by Namikon** [comment]
We talked about that for a while ingame.
The Idea behind this is:
- Gendustry is a pure-luxury mod for bees, you don't *have* to use it, it just makes things a LOT easier
- Mutagen is required, but not ocean-wise, and you can even get it just with redstone and glowstone, the main ressource to craft it at the moment is energy, which is somehow not ideal.

Suggestions how to change it:
- Remove the Mutagen-Producer
- Add the recipe for mutagen to the GT mixer
- Depending on how many of the "bacterial sludge" pools are available on mars, there would be 2 ways:
  - Either allow only BacterialSludge+Uran/Plutonium as recipe (Where plutonium yields more) *or*
  - Also allow water+uran/plutonium to Mutagen, but with lesser yield

Pros:
- Bacterial Sludge has a usage (yay)
- Energy required for the Mutagen is reduced

Cons: 
- You can (if water is not allowed) start mutating bees with gendustry only once you hit mars.

Regarding the "Con" fact: It has to be decided where Gendustry should be tiered in. Mars is somewhat midgame from what we build so far with the oregen. IMHO, I think it's a nice place for that. But as always: You can only be 100% sure once you've tried it yourself

**Comment by Dream-Master** [comment]
Sounds good.

**Comment by Drobac** [comment]
Not sure about it, but need to check if the mutagen is only used in the mutatron and not any of the other machines

**Comment by Namikon** [comment]
Would be nice if you could verify that, but afaik, it is only used to mutate bees together. 
The point is not to make it crazy difficult to get it, but to remove the "too easy" way of getting it. I mean, even I, pre 128EU have enough redstone for months, not to mention the redstone vein I barely touched. So basically, you only use tons of EU to make mutagen, and the machine ignores the "not enough EU/t" problem, so I could setup a mutagen producer, a solar boiler, 32 eu turbine and put in a stack redstone. When I reach gendustry, I have a tank full of Mutagen, yay!

With GT, you would get rid of the useless need for massive EU, but give it a "better" way to make it, by actually using resources that would involve "mutation". The bacterial sludge is just there because it has no other function yet.

Speaking of it: I think the bacterial sludge seas on mars contain at least 300 buckets of sludge each, and they should be pretty common. If that's not the case, there is still the option to make it from water, as I've written above. It needs to be verified that you really can get enough sludge for mutagen before other ways are removed. It should not turn out that you have to pray for a successful mutation because the source of mutagen is limited.

**Comment by Drobac** [comment]
Indeed mutagen is only used in the mutatron to get the new species easily, just checked it

**Comment by Dream-Master** [comment]
I think Bacterial Sludge will be fine. Water is no option maybe a nother fluid use a little bit more to make it. Maybe we add some fluid by our self.

**Comment by Dream-Master** [comment]
Make some Radiactive Bacterial Sludge in the Brewery and this you can make in the Fermenter to Mutagen.

**Comment by Dream-Master** [comment]
In the next update
