### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#15]
Sorted by importance:
1) Ted is working on oceans for RWG. Updating to that version will break your world. Do you have any plan about that?
2) Steve's Carts are pain to tweak. Lots of items with lots of unchangeable mechanics. Removing them from the pack would save a lot of time probably.
3) I see InfernalMobs have standard spawn chance. Is that intentional or overlooked?
4) Thaumcraft Silver Wand Caps crash the game when accessed in Thaumonomicon but I have no idea why.

**Comment by Methes** [comment]
5) Logistic pipes were originally ment to be automation tier before AE2. Right now both systems have equally expensive recipes. Do you want to keep it that way (and make LP an alternative) or change it?
Either way AE2 power requirement is at standard value right now and it should be raised. To at least 4, with LP set to half of that.

**Comment by Dream-Master** [comment]
1 We will see if the Ocean Biomes break the world. Maybe they be on top of the Terrain and not change so much. But i did not see any Update now.
2. I like the mod i take care.
3. I am not sure Arch did some change but i not find any information about that mod. I will generate a new config and will see what it change. Or maybe if you want testing the config by your self change some rarity things.
4. Update my scripts i make a mistake before now its fine.
5. I dont know all the Recipes Arch did. If you have good ideas to nerf the stuff for Mid Game you can nerf it.
6. You can join us on TS because make some discussion much more easier. And why you not on the server. We not building all together. Warlord and Drobac make some base and Chrysator and me. If you want to make your own Base you can do it no Problem.

**Comment by Dream-Master** [comment]
We add Mob Properties to get better control of TF Bosses and Drops but we have to make the config first. You know that Mod ist from Father Toast to like mob ai and Special Mobs.
