### ISSUE TITLE
Draconic Evolution 

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#151]
We have to add ?
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2093099-draconic-evolution-1-0-1c

**Comment by Drobac** [comment]
Would need some more research on it, at first glance appears very powerfull

**Comment by Namikon** [comment]
I have DE on my server, as i wanted some sort of power-storage that looks nice and can keep up with ReactorCraft energy production.
DE can be, in most terms, configured. But trust me, you should install and test it on singleplayer first;
The armor you can craft, even if difficult to do and very expensive (and dangerouos, lol) to make, is same-level (or better) than KAMI. Once you have the top tier tools you can make, your 3x3 tinkers shovel and hammer become foam-toys. (and thats not meant as a joke, test it)

It might have issues with HEE, as it adds a bunch of stuff to the end. I don't want to spoil here, if you want to get spoilers, read the forum thread on the MC forum.

There is a ritual to re-summon a special kind of dragon, which gets more and more difficult each time you do it (and you *have* to do it in order to reach the top tier). This increased difficult is bound to your player. So if the same player summons it a second time, it's more difficult. If  a new players summons him the first time, it's just a regular boosted dragon for him.

All recipes are very hard and expensive to make, but still, the tools and armor might need some adjustment, as the armor for example has twice the flight speed as creative flight, just as an example. As for the recipes: Almost everything after the "basic" items requires nether stars, or even something the dragon drops if you kill him. 

it is, however, something I'd like to see in the top-tier of the pack, once you've beaten all the other things, as a final goal to reach. Maybe one more thing: The pack is RF-based. I'm not sure if it works with EU.

**Comment by Drobac** [comment]
That was my first impression, that you really need big reactor or similar RF production for it to be usefull, although it seem it has some kind off generator itself, if neccesary to produce RF extra util generators can always be enabled. Whenever i did see the tools/ armor in the videos it did seem insanely strong so it might only be viable for extreme late game, prehaps later then all the KAMI items and armor. Do the tools have recipe that can be modified via MT or are there some kind of rituals to get them? Also what does it add i the end that conflicts with HEE? Just ore and structure gen or the dragon mechanics too?

**Comment by Namikon** [comment]
The author has plans to add some kind of multiblock RF-generator too, but there is no sheduled timeframe yet. In order to get the awakened draconium, there is a ritual required, but once you have it all items have regular shaped recipes. I think in order to get all the armor and tools, you have to kill at least 5 dragons. Never been that far in the mod, as it requires an insane amount of resources, even with enderquarry and all other mods maxed out.

Also, with this mod, EU <> RF conversion becomes a point. The largest ball can hold somewhat around 4 Trillion RF, and has INT.MAXVALUE (2 million) limit of how many RF you can input/draw from it. (In the latest version, there is a limit with early-mod energy, but i never played with that.

You can play without RF generators, but then you need a way to get tons of RF, as the dragon-ritual requires a few million RF (I think.. it's 10 Million RF per DraconiumBlock, and you need .. 4 or 5 of them). You could easily tier that into the game with adding power converters.

And for RF > EU, you could enable it only for lategame stuff, by removing shapeless GTEU producer and add one with lategame resources, so, for example, you have to use neutronium plates in order to convert EU to RF. If you are that lategame, it doesn't matter anyways where you get your energy from. And since we don't have big reactors, producing tons of RF for EU is just impossible. (4RF is 1EU afaik, so even for 32 EU/t 1 amp you need to produce 128 RF/t)

Or, you could only add UV producers, so you need to get all transformers and cables in order to use it. That should be the smallest problem

**Comment by Methes** [comment]
Blood Asp added EU -> RF converter in the last update so that should be sorted now...

**Comment by Dream-Master** [comment]
But I can disable the direction i don't want.

**Comment by Methes** [comment]
Yes. And you can use your Fusion Reactor to power the Draconic mod.

**Comment by Namikon** [comment]
Mod is added
