### ISSUE TITLE
Orgen on Galaxy space /Galacticraft Planets

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#152]
I want to finish the orgen to make the Sever update today.
@Namikon I need you for this. (be back at 6 or 7 today)

**Comment by Namikon** [comment]
I'll be there

**Comment by Dream-Master** [comment]
The only thing is Europa have to be empty (only Ledox) otherwise the game crash.
Shematics from galaxy space have to be shift click inside the menu to work iside the Nasa workbench.

**Comment by Dream-Master** [comment]
Ore Mixes dont work on Oberonm Proteus, Io and Callisto.
Phobus and Deimos using Mars Oregen.
Europa crash with ores

**Comment by Namikon** [comment]
Interesting. My guess: It must be Bloodasp's mod, since the different planets generate different Blocks already, so they are using different generators. And basically, if he used that list you sent him, it is impossible that Phobos und Demos generate Mars ores, as they are probably not covered with Mars-blocks.

For Oberon, Proteus io and Callisto, this might be a typo in his code or something. Small ores could also be mixed up, they appear but you don't know which ones are there exactly. Whatever, in order to try a bugfix, I definitely need the up to date sourcecode for galactigreg. And time.

**Comment by Namikon** [comment]
I just downloaded Galactigreg v0.5 from IC2 forum, which has been updated yesterday, and there is absolutely no code that would ever spawn anything in a dimension that is not moon/mars or asteroids.
So what you have is pure experimental code, and you probably should just report that to him

**Comment by Dream-Master** [comment]
Sorry I forget to upload  the pack. Only version 0.6 have the code which isn't online. It's not updated yesterday it's downloaded. I upload the pack before I go working.

**Comment by Dream-Master** [comment]
Maybe you can ask blood asp about the source code and explain him our situation. I send him already a pm with the bugs.

**Comment by Dream-Master** [comment]
Testpack is on Dropbox (2.6.9.4)
https://www.dropbox.com/sh/idgpvg0uilr4e7o/AAARxuTCssv4ndUrpgX6nzuua?dl=0

(I ask again all ready for the source code)

**Comment by Namikon** [comment]
I updated the Sheet on GDrive with all available ingots ingame, and a (personal) opinion about when you first can craft it (By collecting small ores, building machines, a lot of work) and when it becomes easier (Veins, ..stuff..)
Someone should cross-check some things there, as i might haven't seen any recipe.
However, this shall provide us with an easy way to find materials for recipes while tiering mods.

Nice thing is, we do have some ingots that can only be obtained in a very specific way (like centrifuging depleted thorium cells, which requires you to build an entire reactor). So for very special items, there are materials that have an unique way of obtaining it (Instead of the default "a) find vein b) profit" way) I marked these few with a note what the player has to do in order to get this

**Comment by Drobac** [comment]
New Automagy version is out http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2125369-tc4-addon-automagy-automation-and-logistics

**Comment by Dream-Master** [comment]
i know allready in the new pack.Thanks

**Comment by Dream-Master** [comment]
works now
