### ISSUE TITLE
Removing some warp effects

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#166]
I would remove some of the warp effects from WarpTheory because they hinder player with the warp and other players on the server in unneccesary ways and if we will add the new Tainted Magic addon in which some features do require you to have some ammount of warp it would be bad to have all these warp effects.
The effects id like to remove:
Primary requirements
- tongue (unable to send messages) warp effect
- ears (unable to read messages) warp effect
- acceleration warp effect

The first 2 are the chat based effects where you cannot talk to player nor they to you. Even the first warp level you get will trigger them and its not possible to have warp ward on yourself all the time, which mean these effects will be on you constantly ( they basically dont go away unless you suicide ). It wasnt that big of a deal when only i had the effect, but as soon as more player get into Thaumcraft this will wont be  just an annoyance but a big problem (not everyone uses TS and if they do then not all the time).

The third effect causes the day to considerably shorten, think it last less then half its usual duration. Think that the warp effect that one player gets shouldn't effect everyone else.

Secondary wishes
 -chest scramble warp effect
This  one is simply annoying and can be used to grief other player (even unintentionally) - it rearranged all the items in the chests nearby, don't know the range 
- spawn wither warp effect - normal thaumcraft warp already spawns a lot of mobs that can attack a player and are not as destructive to the players base/enviroment, and again can be a problem not just to the player with warp but to a lot of others around him and elsewhere on the map
-random teleport warp effect - extremely annoying especially when you are trying to build anything. The effect randomly teleports the player around for a few minutes

**Comment by Dream-Master** [comment]
What is about the Purification amulet? It takes all warp away or not. Maybe have to looking for a mod that helps.
If you playing with forbidden thing you have to be punished ;-)
Ok maybe the chat thing we can change.
With the day night cycle i cant change much. if i am removing all Warp Theory is useless and i like the mod. Researching forbidden things have to be dangerous and hard. Maybe we have to discuss this with all players.

**Comment by Namikon** [comment]
These warp effects are funny when you have a pack that's based around "don't get warp, ever". But for us, with the actual requirement to GET warp intentional (And the way Azanor has build Thaumcraft, as you just can't get into engame thaumcraft without warp) i also vote to remove them if possible. I haven't seen warp theory at all yet, but from the thaumonomicon, it doesn't have that many items, does it?

But I absolutely second drobac's opinion about these effects. Many of them affect the whole Server, which is not acceptable. And in terms of mobs spawning; The items in this pack are f*ing expensive anyways, a wither spawning in your base and bombing everything to ashes within seconds would result in an instant rage quit for most players.

**Comment by Dream-Master** [comment]
Maybe we can fork the project and change some things because open source and not developed any more.
I dont want to delete this mod. The effects maybe a bit annoying but vanilla Thaumcraft Warp is a joke. It's not dangerous at all. I will keep this mod and maybe change things a bit.
@Namikon are you later in TS?

**Comment by Dream-Master** [comment]
Maybe we have to change the level a bit higher that you get special Effects.

**Comment by Dream-Master** [comment]
Warp events can be changed to a higher level
https://github.com/arkD/WarpTheory/tree/master/src/main/java/shukaro/warptheory/handlers/warpevents

**Comment by Dream-Master** [comment]
Warp toung is on 11 maybe we can change this too

**Comment by Namikon** [comment]
If it's abandoned, we can continue it. Thaumcraft is my dimension anyways, as I've barely played any other mod as intensive as thaumcraft in the past, and my experience with warp is: (Spoilers ahead)

- It's something that Azanor wanted the player to have, until he reaches a certain point where he comes to the conclusion that what he saw is nothing but a trap, the guardians are not evil but want to stop you from falling for the trap, and eventually get rid of most of his warp, which is ( at least with vanilla TC ) a task that will keep you busy for weeks.
- The more you do "evil" stuff, the more effects you'll get. But the longer you don't do anything "bad", the less frequent the warp effects will become (A change azanor made in a recent TC version, and maybe something that warp theory changed back)
- Thaumcraft just makes no sense without getting a single warp point, as many important researches give you warp. So either the warp shall be restricted to everything "undead" and "life creational", or there shall be items that protect you from warp better than the soap and bath salts do. The most "protection" you can get from warp is 30 minutes, and it takes like 10 minutes to craft, if you don't have higher tier thaumcraft machines.
- The sanitizing soap and purifying bath salts are not easy to make, until you can build a decent automation with essentia centrifuges/other essentia stuff.
- The pack shall be hard, shall be tricky, but at no point it shall be unfair. Mixing inventories can lead to item loss due corruption, since we have a different stack-size and most mods work with vanilla 64.
- Spawning any monster that can harm other players is nothing but player griefing, even if it's unintentional
 
I agree that the vanilla thaumcraft warp effects are a bit too weak if you have decent armor, but keep in mind that thaumcraft will be tiered too, and eventually this will cause a "point of no return"; 
The eldritch guardians are no easy enemies, especially on difficult hard, and they can even give you additional warp if you are too far away. It might be that you can't do anything against these effects, because you just can't craft the required items to get protection from warp.

There is no maximum warp, but the item to check your level caps off at 100 warp, which you will never reach by research in vanilla thaumcraft. But due the massive amount of mods we have for thaumcraft, just by doing a lot of research will cause you to get 100 warp in no time.

Maybe the whole warp/evil magic stuff should be rebalanced, as you want it to be hard and unfair, but just today you want to add another mod that requires you to gain (and keep) warp. The really evil effects like teleport and speech-scrambling shall be then tiered to a level above 100. It's impossible to play thaumcraft with 0 warp, but keep it below 100 or even below 75 is a doable task. If you go beyond that point, well, then you shall be punished.

(Just my 2 cents)

**Comment by Dream-Master** [comment]
So we have to rebalancing everything. Maybe we better can talk in Ts about this ?

**Comment by Drobac** [comment]
I was not proposing removing all warp effects, i was merely proposing removing the ones that are harmful to people other then "the Mage" who is the source of warp. That is why i noted the specific warp effects which i believe need to be disabled, there are a lot of warp effects remaining and even if a wither cannot spawn directly in your base does not mean you are safe. Eldritch guardians can also appear, and since we have them on constant infernal they are not easy, not to mention when a horde of mind spider attacks you and you can't kill them quick enough. We have many dangerous warp effects remaining, dont think there arent none. I am merely trying to make sure that we can disabled those that can upset the normal gameplay experience, because you wont be doing thaumcraft 24/7. You will be doing it over a long period of time, especially with the tiering system that is in place and would you really like a wither spawning right in the middle of your storage system? Or right next to your hard earned GT machinery. Sometimes you wont be ready to find a thing like the wither, but we still have opponents that can surprise you and be dangerous.

None of this would be a problem if you could just seperate doing thaumcraft and everything else, but getting the Purification talisman is basically the end game for thaumcraft and is only unlock after you are basically at the top level of warp.

**Comment by Dream-Master** [comment]
We will add a config disabling some Warp Effect in some Diminson. So wither etc...

**Comment by Namikon** [comment]
Namikon/WarpTheory@2a5ee0580804ca77754f9face4991a837fac34e9 will provide a config option for all warp effects. Dim-Blacklist for entity-spawning effects will be added soon (tm)

**Comment by Namikon** [comment]
Update on some WarpEffects: I suggest we should either make some values configurable, or discuss here what shall be set as min/max instead

- Acceleration of time: It has a random lenght of 6000 ticks + (random(0-12000)) ticks, so it lasts at least 300 seconds and worst case 900 seconds which would be 5 to 15 minutes
- Bats: It spawns a random amount of bats between 15 and 45 around you
- Teleport: It teleports you around between 10 and 30 times once you get the effect. It does have a security check however, to only teleport you to a location where the block below you is solid, and the 2 blocks above that one are air
- Blood: Not sure what this does, but it's range is from 64 - 192
- Buff1: Gives you poison effect for 20 seconds
- Buff2: Gives you nausea for 20 seconds
- Buff3: Gives you Jumpboost for 20 seconds
- Buff4: Gives you blindness for 20 seconds
- Chest shuffle: Shuffles a chests inventory, and it will do it with 15 - 45 chests
- Decay: Will decay and compatible plantlife (not only leaves) in a radius of 8 blocks around you. And it will decay 512 to 768 blocks (what..?) before it stops
- Ears: It will make you unable to read chat for 10 to 40 lines of text. Means: It is not time-based; Once you got that effect, the following 10 to 40 lines of chat will be scrambled
- Sound: Will play a soundeffect near you, exactly once
- SoundBehind: Will play a soundeffect (a creeper) directly behind you
- Vanish: This effect seems to be risky; As it replaces blocks below the player with a new tileentity. Even if that is temporary, it can cause corruption if a already existing tileenetity gets replaced by this.
I highly recommed to disable this effect, or maybe redesign it so it would only replace dirt, grass and stone. But then it wont work on other dimensions. And i guess it can even cause bedrock to vanish, as it doesn't have a check for low y-values
- Friend: Spawns a (one) friendly creeper next to you. Not sure if it will turn evil after a while..
- Lighning: Will cause lighning (5-15) around the player
- LivestockRain: It wil rain.. Animals.. around you.. 5 to 15 entities will be spawned
- Rain: Will just cause a world-wide thunderstorm
- Swamp: This will convert the area around you to a swamp. I'm not 100% sure if it will replace all blocks, I can't find any security checks that it wont replace tileentities or non-dirt/stone/grass blocks. This might be as risky as the Vanish effect in terms of world corruption
- Tongue: Same as for Ears, your next 5 to 25 messages will be scrambled
- Wind: I dindn't know there was wind in MC, whatever this does, it does it 5 to 15 times
- Wither: well, yes.. The worst-case, and should be at warp 100, if not higher. And if you really want to add this effect, if needs to be limited to certain dimensions. But it will still do a lot of damage, and be prepared to remove withers in admin mode then after they destroyed a large amount of the dimension it spawned it, as not everyone will be ready to fight the wither when he spawns.

Let the discussion begin.
- What effects shall be altered in what way?
- Which values would be nice to have as config option?

For reference, the following default values are set at the moment for the various effects:
- BatsEffect 15
- TeleportEffect 30
- PoisonEffect 16
- NauseaEffect 25
- JumpEffect 18
- BlindnessEffect 43
- DecayEffect 50
- Ears-Effect 12
- SwampEffect 50
- TongueEffect 11
- CreeperFriendEffect 26
- LiveStockRainEffect 32
- WindEffect 35
- ChestEffect 35
- BloodEffect 25
- AccelerationEffect 27
- LightningEffect 60
- WorldHoleEffect (Fall) 36
- RainEffect 12
- WitherSpawnEffect 70
- FakeBoomEffect 10
- FakeBoomerEffect 10

**Comment by Drobac** [comment]
Im still arguing to completely remove the chat debuffs, if they stay in they should have a max effect of 2 lines of text or similar. Time acceleration affects other players too much so im for complete removal. Wither at 100 warp is ok, that would provide adequate punishment to people who dont look after their warp or try to get too much of a vis regen with the new Tainted magic items.
The wind warp effect just throws the player a few blocks in direction, not very harmful unless you are standing on a platform 100 blocks in the air.
Not sure if the chest effect only works on vanilla chest or iron chests and other containers as well.
Not sure about decay but possibly removes leaves and converts grass  blocks into sand etc.
Swamp replaces blocks like stone into dirt/grass/podzol or even into water blocks and start planting random saplings on dirt blocks around the player.
Friendly creeper stays friendly but seeing a creeper randomly appear next to all your GT machines gives you a heart attack (not recommended for older players).
Blood effect is mostly cosmetic, it makes blood drip from the roof blocks. Looks evil but no bad effects.
Dont know about the vanish effect.
Livestock effect is the funniest one on here, it starts raining random passive mobs on top of you. Especially funny if you are on another planet or space station and you suddenly see a bunch of pork chops and wool falling around you.
Rainstorm effect can be negated by sleeping

Some of the effects can be buffed a bit without much trouble, like the buff1,2,3,4

**Comment by Dream-Master** [comment]
New Warp Theory Version in the next update. Levels and Effects not changed atm.

**Comment by Dream-Master** [comment]
So further Discussion in the Forum Please:

http://www.usrv.eu/mybb/showthread.php?tid=15&pid=19#pid19
