### ISSUE TITLE
Dimension addition.

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#19]
We are using Alpha RWG now. We already ran into an issue with Ocean Bees and other problems might show up.
Ted tweeted "I don't recommend using it right now. Maps will break every update and mod compatibility is not done yet."
I suggest creating a new dimension using something like Mystcraft. This dimension would be plain BoP generation.
Not only would that allow people to get content not available in RWG right now, it would also ease the load on the server if we ever get more players (and therefor solve issues Kirara had before we even encounter them), as they would divide into more dimensions building wherever they like to.

**Comment by Dream-Master** [comment]
Yes i know this problem but now we dont have a Update of RWG with Ocean Biomes and we can't test it. Mystcraft have so much useless stuff if we need only two Dimensions. I want to build in the Overworld with RWG generation not in a second boring generated world. I know you thinking of new Players settle in a new Dimension where they can be proof and get later to the RWG dimension. I look for other solutions too and i testing mystcraft also. So long RWG not updated i dont rush because we have so many things to do. btw you see my core mod i did?

**Comment by Methes** [comment]
Alright, lets wait and see how things work out. Good call.
I've checked your mod and your Thaumcraft recipes and they're both pretty amazing :-).
