### ISSUE TITLE
No fly in some Dimensions

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#92]
No fly in some Dimensions

**Comment by Drobac** [comment]
which would you put other then twilight?

**Comment by Dream-Master** [comment]
Only Twilight at the moment. But we have to talk about that when the mod is done.

**Comment by Namikon** [comment]
All right, some more Information on this:
The no-fly in the OuterLands is only working for Items that enable "creative-hovermode".
So i'm not sure if jetpacks will be affected by this, Drobac could you please test that? If it does, it is basically just 2 lines of code and a new config setting to define nofly-dimensions. Some lines more if I tier the flying ability behind a boss or item or whatever.

But if the jetpack works, then there is nothing I can do without creating a ton of problems.
If a player is flying and the "isFlying" flag is NOT set to true, then I would have to check if he is in the air for longer than x seconds and do *something* about that. But:

- What if he is falling at the moment, and I place him on the ground without falldamage?
- What if I just pop out jetpack items from the armor slot if you have Quantum Armor? Loosing the chest armor is probably something that shouldn't happen in a fight
- What should be done at all if player is in midair for, lets say, 5 seconds? Damage? Blindness? Death? Will he stop flying just by getting effects? Probably not.

Awaiting your comments :)

**Comment by Drobac** [comment]
Outer lands seem to only affect creative type flying, so jetpacks work fine

**Comment by Dream-Master** [comment]
So now we can disable infernal mobs in some Dimension but we don't need it any more;-)

**Comment by Namikon** [comment]
Ok then, shall this issue be closed? Without a complex and smart logic (or disable the usage of specific items) it's not possible to prevent people from flying at all

**Comment by Dream-Master** [comment]
We can limit the flying high? That would be helpful but when it is to complicated we don't have to invest time in that because other important projects.

**Comment by Drobac** [comment]
fly isnt that important as even in the TF dungeons you can bypass a lot of the dungeons juat by building 1x1 dirt towers. There is no other dimension where fly can be used to bypads anything so working on fly restriction(unless very easy to do) is not worth investing time into it

**Comment by Namikon** [comment]
The problem is, there is no (easy) way to check if a player is flying, falling, hovering or somthing else (Without having the isFlying flag set). I would have to keep track of every player's movement over time, and correct it (if that's possible at all) if I think it might be wrong what he did. But this could cause an issue with negating fall damage and such. Personally, I haven't played TF enough to decide on my own if a no-fly mode is required or not; From what I've seen so far, you *do* have to kill all the bosses in a specific order to reach "endgame" there; Not sure ..... damn, drobac posted before I could submit :P But you get the point...

**Comment by Dream-Master** [comment]
Ok let's skip that and looking forward on projects that are more important.
