### ISSUE TITLE
Make a Gloves Mod

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#96]
Make a Gloves Mod for Lava transportation.

**Comment by Drobac** [comment]
What would this be, an armor slot, bauble or what?

**Comment by Dream-Master** [comment]
yes

**Comment by Namikon** [comment]
Gloves added to coremod, see build v0.4.1 or commit 084e5432ac4f73a57dff032c7187d06fa328a9d7

Added:
A glove for your left, and one for your right hand. They go into the "ring" spot in the baubles inventory

What it does:
- Gives permanent Fireprotection 1

But it does that only if all of the following requirements are met:
- Both gloves must be worn, so both Bauble-ring-slots are used
- They must be in the correct spot (Left hand/right hand)
- Any item with *lava* in it's unlocalized name must the the item in your hand (You can have more buckets in your inventory however, the potion effect is a global protection from all sources of fire-damage, so it can't be limited to only your held item)
- If you switch to another item in your hand, the protection runs out (4 seconds timer)
- If you catch on fire (by accident or because you tried to exploit the gloves for cheap lava protection) or if you remove one of the gloves, the potion effect is removed instantly
- The gloves have to be above zero durability, and they will loose 1 durability each 1-3 seconds, as long as they provide you with fire-protection (maybe that needs to be tweaked)
- The add/remove potion effect only occours if you wear the gloves. So using potions to get legit lava/fireproof is still working

@Dream-Master The gloves do not have any recipe by default, you need to provide one (two..) with minetweaker.

**Comment by Namikon** [comment]
Closing issue because it's done. Please report all bugs go to DreamCraft-CoreMod repo

**Comment by Dream-Master** [comment]
Got a Error.

https://gist.github.com/Dream-Master/440580f7fa42085a7e8b#file-gistfile1-txt
